language: android
jdk: oraclejdk8
android:
  components:
    # The SDK version used to compile your project
    - android-25

    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-25.0.2


    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19
    - extra-android-support

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    # - sys-img-armeabi-v7a-android-22
    # - sys-img-armeabi-v7a-android-17
addons:
  apt:
    packages:
      - lynx

script:
  - ./gradlew build connectedCheck
  - if [ -f /home/travis/build/bzzzil/bottles/app/build/outputs/lint-results-debug.html ]; then cat /home/travis/build/bzzzil/bottles/app/build/outputs/lint-results-debug.html; fi
