package io.bzzzil.bottles.database;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;

import io.bzzzil.bottles.R;

public class BottlesSQLiteHelper extends SQLiteOpenHelper {

    /**
     * Database name
     */
    private static final String DATABASE_NAME = "bottles.db";

    /**
     * Database version
     */
    private static final int DATABASE_VERSION = 15;

    public BottlesSQLiteHelper(Context context) {
        super(context, DATABASE_NAME, null, DATABASE_VERSION);
    }

    @Override
    public void onCreate(SQLiteDatabase db) {
        BottlesTable.onCreate(db);
        CountriesTable.onCreate(db);
        insertCountries(db);
    }

    @Override
    public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
        BottlesTable.onUpgrade(db, oldVersion, newVersion);
        CountriesTable.onUpgrade(db, oldVersion, newVersion);
        insertCountries(db);
    }

    private void insertCountries(SQLiteDatabase db)
    {
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('AF', 'Afghanistan', " + R.drawable.afghanistan + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('AL', 'Albania', " + R.drawable.albania + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('DZ', 'Algeria', " + R.drawable.algeria + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('AD', 'Andorra', " + R.drawable.andorra + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('AO', 'Angola', " + R.drawable.angola + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('AG', 'Antigua and Barbuda', " + R.drawable.antigua_and_barbuda + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('AR', 'Argentina', " + R.drawable.argentina + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('AM', 'Armenia', " + R.drawable.armenia + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('AU', 'Australia', " + R.drawable.australia + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('AT', 'Austria', " + R.drawable.austria + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('AZ', 'Azerbaijan', " + R.drawable.azerbaijan + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('BS', 'Bahamas', " + R.drawable.bahamas + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('BH', 'Bahrain', " + R.drawable.bahrain + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('BD', 'Bangladesh', " + R.drawable.bangladesh + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('BB', 'Barbados', " + R.drawable.barbados + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('BY', 'Belarus', " + R.drawable.belarus + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('BE', 'Belgium', " + R.drawable.belgium + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('BZ', 'Belize', " + R.drawable.belize + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('BJ', 'Benin', " + R.drawable.benin + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('BT', 'Bhutan', " + R.drawable.bhutan + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('BO', 'Bolivia', " + R.drawable.bolivia + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('BA', 'Bosnia and Herzegovina', " + R.drawable.bosnia + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('BW', 'Botswana', " + R.drawable.botswana + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('BR', 'Brazil', " + R.drawable.brazil + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('VG', 'British Virgin Islands', " + R.drawable.british_virgin_islands + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('BN', 'Brunei', " + R.drawable.brunei + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('BG', 'Bulgaria', " + R.drawable.bulgaria + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('BF', 'Burkina Faso', " + R.drawable.burkina_faso + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('BI', 'Burundi', " + R.drawable.burundi + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('KH', 'Cambodia', " + R.drawable.cambodia + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('CM', 'Cameroon', " + R.drawable.cameroon + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('CA', 'Canada', " + R.drawable.canada + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('CV', 'Cape Verde', " + R.drawable.cape_verde + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('CF', 'Central African Republic', " + R.drawable.central_african_republic + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('TD', 'Chad', " + R.drawable.chad + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('CL', 'Chile', " + R.drawable.chile + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('CN', 'China', " + R.drawable.china +  ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('CX', 'Christmas Island', " + R.drawable.christmas_island + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('CO', 'Colombia', " + R.drawable.colombia + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('KM', 'Comoros', " + R.drawable.comoros + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('CK', 'Cook Islands', " + R.drawable.cook_islands + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('CR', 'Costa Rica', " + R.drawable.costa_rica + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('CI', 'Cote d'Ivoire'. " + R.drawable.cote_divoire + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('HR', 'Croatia', " + R.drawable.croatia + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('CU', 'Cuba', " + R.drawable.cuba + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('CY', 'Cyprus', " + R.drawable.cyprus + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('CZ', 'Czech Republic', " + R.drawable.czech_republic + ")");
/*        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('DK', 'Denmark', " + R.drawable.Denmark + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('DJ', 'Djibouti', " + R.drawable.Djibouti + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('DM', 'Dominica', " + R.drawable.Dominica + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('DO', 'Dominican Republic', " + R.drawable.Dominican Republic + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('EC', 'Ecuador', " + R.drawable.Ecuador + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('EG', 'Egypt', " + R.drawable.Egypt + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('SV', 'El Salvador', " + R.drawable.El Salvador + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('GQ', 'Equatorial Guinea', " + R.drawable.Equatorial Guinea + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('ER', 'Eritrea', " + R.drawable.Eritrea + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('EE', 'Estonia', " + R.drawable.Estonia + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('ET', 'Ethiopia', " + R.drawable.Ethiopia + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('FJ', 'Fiji', " + R.drawable.Fiji + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('FI', 'Finland', " + R.drawable.Finland + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('FR', 'France', " + R.drawable.France + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('GA', 'Gabon', " + R.drawable.Gabon + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('GM', '"Gambia; The";"Gambia; The" + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('GE', 'Georgia', " + R.drawable.Georgia + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('DE', 'Germany', " + R.drawable.Germany + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('GH', 'Ghana', " + R.drawable.Ghana + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('GR', 'Greece', " + R.drawable.Greece + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('GD', 'Grenada', " + R.drawable.Grenada + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('GT', 'Guatemala', " + R.drawable.Guatemala + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('GN', 'Guinea', " + R.drawable.Guinea + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('GW', 'Guinea-Bissau', " + R.drawable.Guinea-Bissau + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('GY', 'Guyana', " + R.drawable.Guyana + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('HT', 'Haiti', " + R.drawable.Haiti + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('HN', 'Honduras', " + R.drawable.Honduras + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('HU', 'Hungary', " + R.drawable.Hungary + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('IS', 'Iceland', " + R.drawable.Iceland + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('IN', 'India', " + R.drawable.India + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('ID', 'Indonesia', " + R.drawable.Indonesia + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('IR', 'Iran', " + R.drawable.Iran + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('IQ', 'Iraq', " + R.drawable.Iraq + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('IE', 'Ireland', " + R.drawable.Ireland + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('IL', 'Israel', " + R.drawable.Israel + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('IT', 'Italy', " + R.drawable.Italy + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('JM', 'Jamaica', " + R.drawable.Jamaica + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('JP', 'Japan', " + R.drawable.Japan + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('JO', 'Jordan', " + R.drawable.Jordan + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('KZ', 'Kazakhstan', " + R.drawable.Kazakhstan + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('KE', 'Kenya', " + R.drawable.Kenya + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('KI', 'Kiribati', " + R.drawable.Kiribati + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('KP', '"Korea; North";"Korea; North" + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('KR', '"Korea; South";"Korea; South" + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('KW', 'Kuwait', " + R.drawable.Kuwait + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('KG', 'Kyrgyzstan', " + R.drawable.Kyrgyzstan + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('LA', 'Laos', " + R.drawable.Laos + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('LV', 'Latvia', " + R.drawable.Latvia + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('LB', 'Lebanon', " + R.drawable.Lebanon + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('LS', 'Lesotho', " + R.drawable.Lesotho + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('LR', 'Liberia', " + R.drawable.Liberia + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('LY', 'Libya', " + R.drawable.Libya + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('LI', 'Liechtenstein', " + R.drawable.Liechtenstein + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('LT', 'Lithuania', " + R.drawable.Lithuania + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('LU', 'Luxembourg', " + R.drawable.Luxembourg + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('MK', 'Macedonia', " + R.drawable.Macedonia + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('MG', 'Madagascar', " + R.drawable.Madagascar + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('MW', 'Malawi', " + R.drawable.Malawi + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('MY', 'Malaysia', " + R.drawable.Malaysia + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('MV', 'Maldives', " + R.drawable.Maldives + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('ML', 'Mali', " + R.drawable.Mali + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('MT', 'Malta', " + R.drawable.Malta + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('MH', 'Marshall Islands', " + R.drawable.Marshall Islands + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('MR', 'Mauritania', " + R.drawable.Mauritania + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('MU', 'Mauritius', " + R.drawable.Mauritius + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('MX', 'Mexico', " + R.drawable.Mexico + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('FM', 'Micronesia', " + R.drawable.Micronesia + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('MD', 'Moldova', " + R.drawable.Moldova + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('MC', 'Monaco', " + R.drawable.Monaco + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('MN', 'Mongolia', " + R.drawable.Mongolia + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('ME', 'Montenegro', " + R.drawable.Montenegro + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('MA', 'Morocco', " + R.drawable.Morocco + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('MZ', 'Mozambique', " + R.drawable.Mozambique + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('MM', 'Myanmar (Burma);Myanmar (Burma) + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('NA', 'Namibia', " + R.drawable.Namibia + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('NR', 'Nauru', " + R.drawable.Nauru + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('NP', 'Nepal', " + R.drawable.Nepal + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('NL', 'Netherlands', " + R.drawable.Netherlands + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('NZ', 'New Zealand', " + R.drawable.New Zealand + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('NI', 'Nicaragua', " + R.drawable.Nicaragua + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('NE', 'Niger', " + R.drawable.Niger + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('NG', 'Nigeria', " + R.drawable.Nigeria + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('NO', 'Norway', " + R.drawable.Norway + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('OM', 'Oman', " + R.drawable.Oman + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('PK', 'Pakistan', " + R.drawable.Pakistan + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('PW', 'Palau', " + R.drawable.Palau + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('PA', 'Panama', " + R.drawable.Panama + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('PG', 'Papua New Guinea', " + R.drawable.Papua New Guinea + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('PY', 'Paraguay', " + R.drawable.Paraguay + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('PE', 'Peru', " + R.drawable.Peru + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('PH', 'Philippines', " + R.drawable.Philippines + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('PL', 'Poland', " + R.drawable.Poland + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('PT', 'Portugal', " + R.drawable.Portugal + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('QA', 'Qatar', " + R.drawable.Qatar + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('RO', 'Romania', " + R.drawable.Romania + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('RU', 'Russia', " + R.drawable.Russia + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('RW', 'Rwanda', " + R.drawable.Rwanda + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('KN', 'Saint Kitts and Nevis', " + R.drawable.Saint Kitts and Nevis + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('LC', 'Saint Lucia', " + R.drawable.Saint Lucia + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('VC', 'Saint Vincent and the Grenadines', " + R.drawable.Saint Vincent and the Grenadines + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('WS', 'Samoa', " + R.drawable.Samoa + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('SM', 'San Marino', " + R.drawable.San Marino + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('ST', 'Sao Tome and Principe', " + R.drawable.Sao Tome and Principe + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('SA', 'Saudi Arabia', " + R.drawable.Saudi Arabia + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('SN', 'Senegal', " + R.drawable.Senegal + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('RS', 'Serbia', " + R.drawable.Serbia + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('SC', 'Seychelles', " + R.drawable.Seychelles + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('SL', 'Sierra Leone', " + R.drawable.Sierra Leone + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('SG', 'Singapore', " + R.drawable.Singapore + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('SK', 'Slovakia', " + R.drawable.Slovakia + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('SI', 'Slovenia', " + R.drawable.Slovenia + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('SB', 'Solomon Islands', " + R.drawable.Solomon Islands + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('SO', 'Somalia', " + R.drawable.Somalia + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('ZA', 'South Africa', " + R.drawable.South Africa + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('ES', 'Spain', " + R.drawable.Spain + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('LK', 'Sri Lanka', " + R.drawable.Sri Lanka + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('SD', 'Sudan', " + R.drawable.Sudan + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('SR', 'Suriname', " + R.drawable.Suriname + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('SZ', 'Swaziland', " + R.drawable.Swaziland + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('SE', 'Sweden', " + R.drawable.Sweden + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('CH', 'Switzerland', " + R.drawable.Switzerland + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('SY', 'Syria', " + R.drawable.Syria + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('TJ', 'Tajikistan', " + R.drawable.Tajikistan + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('TZ', 'Tanzania', " + R.drawable.Tanzania + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('TH', 'Thailand', " + R.drawable.Thailand + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('TL', 'Timor-Leste (East Timor);Timor-Leste (East Timor) + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('TG', 'Togo', " + R.drawable.Togo + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('TO', 'Tonga', " + R.drawable.Tonga + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('TT', 'Trinidad and Tobago', " + R.drawable.Trinidad and Tobago + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('TN', 'Tunisia', " + R.drawable.Tunisia + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('TR', 'Turkey', " + R.drawable.Turkey + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('TM', 'Turkmenistan', " + R.drawable.Turkmenistan + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('TV', 'Tuvalu', " + R.drawable.Tuvalu + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('UG', 'Uganda', " + R.drawable.Uganda + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('UA', 'Ukraine', " + R.drawable.Ukraine + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('AE', 'United Arab Emirates', " + R.drawable.United Arab Emirates + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('GB', 'United Kingdom', " + R.drawable.United Kingdom + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('US', 'United States', " + R.drawable.United States + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('UY', 'Uruguay', " + R.drawable.Uruguay + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('UZ', 'Uzbekistan', " + R.drawable.Uzbekistan + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('VU', 'Vanuatu', " + R.drawable.Vanuatu + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('VA', 'Vatican City', " + R.drawable.Vatican City + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('VE', 'Venezuela', " + R.drawable.Venezuela + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('VN', 'Vietnam', " + R.drawable.Vietnam + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('YE', 'Yemen', " + R.drawable.Yemen + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('ZM', 'Zambia', " + R.drawable.Zambia + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('ZW', 'Zimbabwe', " + R.drawable.Zimbabwe + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('GE', 'Abkhazia', " + R.drawable.Abkhazia + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('TW', '"China; Republic of (Taiwan)";"China; Republic of (Taiwan)" + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('AZ', 'Nagorno-Karabakh', " + R.drawable.Nagorno-Karabakh + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('CY', 'Northern Cyprus', " + R.drawable.Northern Cyprus + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('MD', 'Pridnestrovie (Transnistria);Pridnestrovie (Transnistria) + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('SO', 'Somaliland', " + R.drawable.Somaliland + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('GE', 'South Ossetia', " + R.drawable.South Ossetia + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('AU', 'Ashmore and Cartier Islands', " + R.drawable.Ashmore and Cartier Islands + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('CC', 'Cocos (Keeling) Islands', " + R.drawable.Cocos (Keeling) Islands + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('AU', 'Coral Sea Islands', " + R.drawable.Coral Sea Islands + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('HM', 'Heard Island and McDonald Islands', " + R.drawable.Heard Island and McDonald Islands + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('NF', 'Norfolk Island', " + R.drawable.Norfolk Island + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('NC', 'New Caledonia', " + R.drawable.New Caledonia + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('PF', 'French Polynesia', " + R.drawable.French Polynesia + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('YT', 'Mayotte', " + R.drawable.Mayotte + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('GP', 'Saint Barthelemy', " + R.drawable.Saint Barthelemy + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('GP', 'Saint Martin', " + R.drawable.Saint Martin + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('PM', 'Saint Pierre and Miquelon', " + R.drawable.Saint Pierre and Miquelon + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('WF', 'Wallis and Futuna', " + R.drawable.Wallis and Futuna + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('TF', 'French Southern and Antarctic Lands', " + R.drawable.French Southern and Antarctic Lands + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('PF', 'Clipperton Island', " + R.drawable.Clipperton Island + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('BV', 'Bouvet Island', " + R.drawable.Bouvet Island + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('NU', 'Niue', " + R.drawable.Niue + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('TK', 'Tokelau', " + R.drawable.Tokelau + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('GG', 'Guernsey', " + R.drawable.Guernsey + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('IM', 'Isle of Man', " + R.drawable.Isle of Man + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('JE', 'Jersey', " + R.drawable.Jersey + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('AI', 'Anguilla', " + R.drawable.Anguilla + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('BM', 'Bermuda', " + R.drawable.Bermuda + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('IO', 'British Indian Ocean Territory', " + R.drawable.British Indian Ocean Territory + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('KY', 'Cayman Islands', " + R.drawable.Cayman Islands + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('FK', 'Falkland Islands (Islas Malvinas);Falkland Islands (Islas Malvinas) + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('GI', 'Gibraltar', " + R.drawable.Gibraltar + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('MS', 'Montserrat', " + R.drawable.Montserrat + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('PN', 'Pitcairn Islands', " + R.drawable.Pitcairn Islands + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('SH', 'Saint Helena', " + R.drawable.Saint Helena + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('GS', 'South Georgia & South Sandwich Islands', " + R.drawable.South Georgia & South Sandwich Islands + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('TC', 'Turks and Caicos Islands', " + R.drawable.Turks and Caicos Islands + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('MP', 'Northern Mariana Islands', " + R.drawable.Northern Mariana Islands + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('PR', 'Puerto Rico', " + R.drawable.Puerto Rico + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('AS', 'American Samoa', " + R.drawable.American Samoa + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('UM', 'Baker Island', " + R.drawable.Baker Island + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('GU', 'Guam', " + R.drawable.Guam + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('UM', 'Howland Island', " + R.drawable.Howland Island + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('UM', 'Jarvis Island', " + R.drawable.Jarvis Island + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('UM', 'Johnston Atoll', " + R.drawable.Johnston Atoll + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('UM', 'Kingman Reef', " + R.drawable.Kingman Reef + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('UM', 'Midway Islands', " + R.drawable.Midway Islands + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('UM', 'Navassa Island', " + R.drawable.Navassa Island + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('UM', 'Palmyra Atoll', " + R.drawable.Palmyra Atoll + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('VI', 'U.S. Virgin Islands', " + R.drawable.U.S. Virgin Islands + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('UM', 'Wake Island', " + R.drawable.Wake Island + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('HK', 'Hong Kong', " + R.drawable.Hong Kong + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('MO', 'Macau', " + R.drawable.Macau + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('FO', 'Faroe Islands', " + R.drawable.Faroe Islands + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('GL', 'Greenland', " + R.drawable.Greenland + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('GF', 'French Guiana', " + R.drawable.French Guiana + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('GP', 'Guadeloupe', " + R.drawable.Guadeloupe + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('MQ', 'Martinique', " + R.drawable.Martinique + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('RE', 'Reunion', " + R.drawable.Reunion + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('AX', 'Aland', " + R.drawable.Aland + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('AW', 'Aruba', " + R.drawable.Aruba + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('AN', 'Netherlands Antilles', " + R.drawable.Netherlands Antilles + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('SJ', 'Svalbard', " + R.drawable.Svalbard + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('AC', 'Ascension', " + R.drawable.Ascension + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('TA', 'Tristan da Cunha', " + R.drawable.Tristan da Cunha + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('AQ', 'Australian Antarctic Territory', " + R.drawable.Australian Antarctic Territory + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('AQ', 'Ross Dependency', " + R.drawable.Ross Dependency + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('AQ', 'Peter I Island', " + R.drawable.Peter I Island + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('AQ', 'Queen Maud Land', " + R.drawable.Queen Maud Land + ")");
        db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('AQ', 'British Antarctic Territory', " + R.drawable.British Antarctic Territory + ")");
            db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('CD', '"Congo; (Congo  Kinshasa)";"Congo; (Congo  Kinshasa)" + ")");
            db.execSQL("insert into " + CountriesTable.TABLE_COUNTRIES + " values ('CG', '"Congo; (Congo  Brazzaville)";"Congo; (Congo  Brazzaville)" + ")");*/
    }
}
